# Book settings
title: euclidlib
author: the euclidlib team
logo: euclidlib-patch.png

# Notebook execution
execute:
  execute_notebooks: force

# LaTeX config
latex:
  latex_documents:
    targetname: book.tex

# Bibliography
bibtex_bibfiles:
  - references.bib

# Sphinx-specific config overrides
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
